Version: 1

# SQLITE / MYSQL / JSON / MONGODB
DatabaseType: SQLITE
#Use Database only for MYSQL Connections!
MYSQL:
  Host: "localhost"
  Port: "3306"
  Database: "DatabaseName"
  Username: "root"
  Password: "Password"
MongoDB:
  Host: "localhost"
  Port: "3306"
  Database: "DatabaseName"
  Username: "root"
  Password: "Password"